-- Generated from prisma/schema.prisma. Run `npx prisma migrate deploy`.
CREATE TABLE `roles` (`id` INTEGER NOT NULL AUTO_INCREMENT, `name` ENUM('ADMIN','PROJECT_MANAGER','STAFF','VIEWER') NOT NULL, `description` VARCHAR(255) NULL, UNIQUE INDEX `roles_name_key`(`name`), PRIMARY KEY (`id`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `users` (`id` INTEGER NOT NULL AUTO_INCREMENT, `name` VARCHAR(120) NOT NULL, `email` VARCHAR(190) NOT NULL, `password_hash` VARCHAR(255) NOT NULL, `refresh_token_hash` VARCHAR(255) NULL, `phone` VARCHAR(24) NULL, `role_id` INTEGER NOT NULL, `is_active` BOOLEAN NOT NULL DEFAULT true, `must_change_password` BOOLEAN NOT NULL DEFAULT false, `last_login_at` DATETIME(3) NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL, UNIQUE INDEX `users_email_key`(`email`), PRIMARY KEY (`id`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `store_types` (`id` INTEGER NOT NULL AUTO_INCREMENT, `name` VARCHAR(80) NOT NULL, `is_active` BOOLEAN NOT NULL DEFAULT true, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), UNIQUE INDEX `store_types_name_key`(`name`), PRIMARY KEY (`id`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `sites` (`id` INTEGER NOT NULL AUTO_INCREMENT, `project_type` ENUM('NSO','RENEWAL','RELOCATION','OTHER') NOT NULL DEFAULT 'NSO', `highlands_status` ENUM('PENDING','ON_PROGRESS','DONE','CANCELLED') NOT NULL DEFAULT 'PENDING', `province` VARCHAR(100) NOT NULL, `tax_code` VARCHAR(30) NULL, `store_type_id` INTEGER NULL, `store_name` VARCHAR(190) NOT NULL, `address` TEXT NOT NULL, `site_possession_date` DATE NULL, `highlands_pic_name` VARCHAR(120) NULL, `highlands_pic_phone` VARCHAR(24) NULL, `viettel_signal_handover_date` DATE NULL, `ftel_contract_number` VARCHAR(80) NULL, `pppoe_username` VARCHAR(120) NULL, `pppoe_password_encrypted` TEXT NULL, `online_date_time` DATETIME(3) NULL, `configuration_completed_at` DATETIME(3) NULL, `outdoor_status` ENUM('NOT_STARTED','SURVEYING','DEPLOYING','COMPLETED','BLOCKED') NOT NULL DEFAULT 'NOT_STARTED', `indoor_status` ENUM('NOT_STARTED','SURVEYING','DEPLOYING','COMPLETED','BLOCKED') NOT NULL DEFAULT 'NOT_STARTED', `infrastructure_completed_date` DATE NULL, `survey_contact_phone` VARCHAR(24) NULL, `note` TEXT NULL, `issue_status` ENUM('NONE','OPEN','RESOLVED') NOT NULL DEFAULT 'NONE', `issue_content` TEXT NULL, `target_online_at` DATETIME(3) NULL, `created_by` INTEGER NOT NULL, `updated_by` INTEGER NOT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL, `deleted_at` DATETIME(3) NULL, INDEX `sites_highlands_status_idx`(`highlands_status`), INDEX `sites_province_idx`(`province`), INDEX `sites_store_name_idx`(`store_name`), INDEX `sites_tax_code_idx`(`tax_code`), INDEX `sites_site_possession_date_idx`(`site_possession_date`), INDEX `sites_online_date_time_idx`(`online_date_time`), INDEX `sites_target_online_at_idx`(`target_online_at`), INDEX `sites_deleted_at_idx`(`deleted_at`), PRIMARY KEY (`id`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `site_notes` (`id` INTEGER NOT NULL AUTO_INCREMENT, `site_id` INTEGER NOT NULL, `content` TEXT NOT NULL, `created_by` INTEGER NOT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), INDEX `site_notes_site_id_created_at_idx`(`site_id`, `created_at`), PRIMARY KEY (`id`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `reminders` (`id` INTEGER NOT NULL AUTO_INCREMENT, `site_id` INTEGER NULL, `title` VARCHAR(190) NOT NULL, `description` TEXT NULL, `due_at` DATETIME(3) NOT NULL, `priority` ENUM('LOW','MEDIUM','HIGH','URGENT') NOT NULL DEFAULT 'MEDIUM', `status` ENUM('OPEN','DONE','CANCELLED') NOT NULL DEFAULT 'OPEN', `assignee_id` INTEGER NOT NULL, `created_by` INTEGER NOT NULL, `completed_at` DATETIME(3) NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL, INDEX `reminders_assignee_id_status_due_at_idx`(`assignee_id`, `status`, `due_at`), INDEX `reminders_site_id_idx`(`site_id`), PRIMARY KEY (`id`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `audit_logs` (`id` BIGINT NOT NULL AUTO_INCREMENT, `user_id` INTEGER NULL, `action` VARCHAR(80) NOT NULL, `entity_type` VARCHAR(80) NOT NULL, `entity_id` VARCHAR(80) NULL, `field_name` VARCHAR(100) NULL, `old_value` TEXT NULL, `new_value` TEXT NULL, `ip_address` VARCHAR(64) NULL, `user_agent` VARCHAR(500) NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), INDEX `audit_logs_entity_type_entity_id_idx`(`entity_type`, `entity_id`), INDEX `audit_logs_created_at_idx`(`created_at`), PRIMARY KEY (`id`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `users` ADD CONSTRAINT `users_role_id_fkey` FOREIGN KEY (`role_id`) REFERENCES `roles`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE `sites` ADD CONSTRAINT `sites_store_type_id_fkey` FOREIGN KEY (`store_type_id`) REFERENCES `store_types`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `sites` ADD CONSTRAINT `sites_created_by_fkey` FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE `sites` ADD CONSTRAINT `sites_updated_by_fkey` FOREIGN KEY (`updated_by`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE `site_notes` ADD CONSTRAINT `site_notes_site_id_fkey` FOREIGN KEY (`site_id`) REFERENCES `sites`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `site_notes` ADD CONSTRAINT `site_notes_created_by_fkey` FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE `reminders` ADD CONSTRAINT `reminders_site_id_fkey` FOREIGN KEY (`site_id`) REFERENCES `sites`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `reminders` ADD CONSTRAINT `reminders_assignee_id_fkey` FOREIGN KEY (`assignee_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE `reminders` ADD CONSTRAINT `reminders_created_by_fkey` FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE `audit_logs` ADD CONSTRAINT `audit_logs_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
